### ISSUE TITLE
Métodos GET-POST-PUT-DELETE 

### ISSUE THREAD

**Issue by Nerk1** [gti-sos/SOS1920-24#17]
Desplegar los métodos en las diferentes casuísticas:
- Para recursos generales:
      · GET: Debe devolver una lista con todos los recursos.
      · POST: Debe crear un nuevo recurso.
      · PUT: Debe devolver error de operacion no permitida.
      · DELETE: Debe borrar todos los recursos.
- Para recursos concretos:
      · GET: Devuelve el recurso concreto.
      · POST: Debe devolver error de operacion no permitida.
      · PUT: Debe actualizar ese recurso.
      · DELETE: Debe borrar el recurso.

Siguiendo esta implementación se cumplen las normativas de la "TABLA AZUL".

**Comment by vicpaltor** [comment]
ok
