### ISSUE TITLE
Pruebas con POSTMAN (Leer Descripcion)

### ISSUE THREAD

**Issue by Nerk1** [gti-sos/SOS1920-24#18]
Una vez implementado los recursos o en el desarrollo de cada uno, implementar las pruebas necesarias con POSTMAN para que de los mensajes reflejados en la ISSUE de los métodos.

1º Una vez Implementado en GOORM, diseñar las pruebas para GOORM, de manera que NO se hagan sobre recursos FUNCIONALES. Se CREA, se MODIFICA y se BORRA el mismo recurso que utilizamos para las pruebas.

2º Una vez testeado y pasados todos los test Implementar en HEROKU.

3º Implementar todos los test de nuevo en POSTMAN frente a HEROKU.

Debemos tener al final 2 Collection Runner en POSTMAN, uno contra los recursos en GOORM y otro contra los recursos en HEROKU.

Asegurarse en las pruebas que se envian los mensajes de la "TABLA VERDE" del Lab 06

**Comment by vicpaltor** [comment]
ok
